spring:
  data:
    redis:
      database: 1
      host: muteki.top
      port: 6379
      password: xzx123
      timeout: 6000ms  # 连接超时时长（毫秒）
  datasource:
    # MySQL8
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://muteki.top:3306/intelligent_community?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: xzx123
    hikari:
      connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
      minimum-idle: 2               # 最小空闲连接数
      maximum-pool-size: 10         # 最大连接数
      auto-commit: true             # 自动提交
      idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
      connection-test-query: SELECT 1
      pool-name: MyHikariCP

#storage:
#  enabled: true
#  config:
#    # 存储类型：local、aliyun、minio
#    type: local
#    domain: http://localhost:8080
#  local:
#    path: /Users/cjq/Documents/upload

#storage:
#  enabled: true
#  config:
#    type: minio
#  minio:
#    access-key: admin
#    secret-key: 12345678
#    end-point: http://43.137.12.232:9000
#    bucket-name: images

#storage:
#  enabled: true
#  config:
#    type: aliyun
#    domain: https://mqxu-oss.oss-cn-hangzhou.aliyuncs.com
#  aliyun:
#    access-key-id: xxxxx
#    access-key-secret: xxxxx
#    end-point: oss-cn-hangzhou.aliyuncs.com
#    bucket-name: mqxu-oss

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: -1
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false